# Generated by Django 3.0.3 on 2020-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=50)),
                ('Positive', models.FloatField(max_length=50)),
                ('Negative', models.FloatField(max_length=50)),
                ('score', models.TextField()),
            ],
        ),
    ]
